baseURL = "https://aronifanger.github.com/"
languageCode = "en-us"
title = "Aron Ifanger"
theme = "hugo-theme-m10c-master"
avatar = "avatar.jpg"

paginate = 5

[params]
  author = "Aron Ifanger"
  description = "BSc Computational Mathematics degree, MSc Computer Science degree and Data Scientist at Semantix"
  [[params.social]]
    name = "github"
    url = "https://github.com/aronifanger"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/aronifanger/"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
